In [1]:
import re
import pandas as pd

def robust_contraction_processor(df):
    """
    Extremely robust contraction processor that handles all apostrophe types
    and various text positions.
    """
    # Define all possible apostrophe characters and their code points
    apostrophe_chars = {
        "'": 39,    # STRAIGHT APOSTROPHE (U+0027)
        "'": 8217,  # RIGHT SINGLE QUOTE (U+2019) - THIS IS THE ONE IN YOUR TEXT
        "'": 8216,  # LEFT SINGLE QUOTE (U+2018)
        "`": 96,    # GRAVE ACCENT (U+0060)
        "′": 8242,  # PRIME (U+2032)
        "´": 180    # ACUTE ACCENT (U+00B4)
    }
    
    # Create a special RIGHT SINGLE QUOTE for explicit matching
    RIGHT_QUOTE = chr(8217)  # This is the apostrophe in your text
    
    processed_texts = []
    
    for index, row in df.iterrows():
        text = str(row['text'])
        original = text
        
        # Step 1: Normalize whitespace
        text = ' '.join(text.split())
        
        # Step 2: Direct replacements with EXPLICIT RIGHT SINGLE QUOTE
        # This ensures we're using the EXACT character in your text
        
        # let's → let us (covering all positions and surrounding characters)
        text = text.replace(f"let{RIGHT_QUOTE}s ", "let us ")
        text = text.replace(f"Let{RIGHT_QUOTE}s ", "Let us ")
        text = text.replace(f"let{RIGHT_QUOTE}s.", "let us.")
        text = text.replace(f"Let{RIGHT_QUOTE}s.", "Let us.")
        text = text.replace(f"let{RIGHT_QUOTE}s,", "let us,")
        text = text.replace(f"Let{RIGHT_QUOTE}s,", "Let us,")
        text = text.replace(f"let{RIGHT_QUOTE}s!", "let us!")
        text = text.replace(f"Let{RIGHT_QUOTE}s!", "Let us!")
        text = text.replace(f"let{RIGHT_QUOTE}s?", "let us?")
        text = text.replace(f"Let{RIGHT_QUOTE}s?", "Let us?")
        
        # I'm → I am
        text = text.replace(f"I{RIGHT_QUOTE}m ", "I am ")
        text = text.replace(f"i{RIGHT_QUOTE}m ", "I am ")
        text = text.replace(f"I{RIGHT_QUOTE}m.", "I am.")
        text = text.replace(f"I{RIGHT_QUOTE}m,", "I am,")
        text = text.replace(f"I{RIGHT_QUOTE}m!", "I am!")
        text = text.replace(f"I{RIGHT_QUOTE}m?", "I am?")
        
        # don't → do not
        text = text.replace(f"don{RIGHT_QUOTE}t ", "do not ")
        text = text.replace(f"Don{RIGHT_QUOTE}t ", "Do not ")
        text = text.replace(f"don{RIGHT_QUOTE}t.", "do not.")
        text = text.replace(f"Don{RIGHT_QUOTE}t.", "Do not.")
        text = text.replace(f"don{RIGHT_QUOTE}t,", "do not,")
        text = text.replace(f"Don{RIGHT_QUOTE}t,", "Do not,")
        text = text.replace(f"don{RIGHT_QUOTE}t!", "do not!")
        text = text.replace(f"Don{RIGHT_QUOTE}t!", "Do not!")
        text = text.replace(f"don{RIGHT_QUOTE}t?", "do not?")
        text = text.replace(f"Don{RIGHT_QUOTE}t?", "Do not?")
        
        # must've → must have (this wasn't working before)
        text = text.replace(f"must{RIGHT_QUOTE}ve ", "must have ")
        text = text.replace(f"Must{RIGHT_QUOTE}ve ", "Must have ")
        text = text.replace(f"must{RIGHT_QUOTE}ve.", "must have.")
        text = text.replace(f"Must{RIGHT_QUOTE}ve.", "Must have.")
        text = text.replace(f"must{RIGHT_QUOTE}ve,", "must have,")
        text = text.replace(f"Must{RIGHT_QUOTE}ve,", "Must have,")
        text = text.replace(f"must{RIGHT_QUOTE}ve!", "must have!")
        text = text.replace(f"Must{RIGHT_QUOTE}ve!", "Must have!")
        text = text.replace(f"must{RIGHT_QUOTE}ve?", "must have?")
        text = text.replace(f"Must{RIGHT_QUOTE}ve?", "Must have?")
        
        # you're → you are
        text = text.replace(f"you{RIGHT_QUOTE}re ", "you are ")
        text = text.replace(f"You{RIGHT_QUOTE}re ", "You are ")
        text = text.replace(f"you{RIGHT_QUOTE}re.", "you are.")
        text = text.replace(f"You{RIGHT_QUOTE}re.", "You are.")
        text = text.replace(f"you{RIGHT_QUOTE}re,", "you are,")
        text = text.replace(f"You{RIGHT_QUOTE}re,", "You are,")
        text = text.replace(f"you{RIGHT_QUOTE}re!", "you are!")
        text = text.replace(f"You{RIGHT_QUOTE}re!", "You are!")
        text = text.replace(f"you{RIGHT_QUOTE}re?", "you are?")
        text = text.replace(f"You{RIGHT_QUOTE}re?", "You are?")
        
        # you'll → you will (adding this based on missing examples)
        text = text.replace(f"you{RIGHT_QUOTE}ll ", "you will ")
        text = text.replace(f"You{RIGHT_QUOTE}ll ", "You will ")
        text = text.replace(f"you{RIGHT_QUOTE}ll.", "you will.")
        text = text.replace(f"You{RIGHT_QUOTE}ll.", "You will.")
        text = text.replace(f"you{RIGHT_QUOTE}ll,", "you will,")
        text = text.replace(f"You{RIGHT_QUOTE}ll,", "You will,")
        
        # there'll → there will (adding this based on missing examples)
        text = text.replace(f"there{RIGHT_QUOTE}ll ", "there will ")
        text = text.replace(f"There{RIGHT_QUOTE}ll ", "There will ")
        text = text.replace(f"there{RIGHT_QUOTE}ll.", "there will.")
        text = text.replace(f"There{RIGHT_QUOTE}ll.", "There will.")
        text = text.replace(f"there{RIGHT_QUOTE}ll,", "there will,")
        text = text.replace(f"There{RIGHT_QUOTE}ll,", "There will,")
        
        # they're → they are
        text = text.replace(f"they{RIGHT_QUOTE}re ", "they are ")
        text = text.replace(f"They{RIGHT_QUOTE}re ", "They are ")
        text = text.replace(f"they{RIGHT_QUOTE}re.", "they are.")
        text = text.replace(f"They{RIGHT_QUOTE}re.", "They are.")
        
        # it's → it is
        text = text.replace(f"it{RIGHT_QUOTE}s ", "it is ")
        text = text.replace(f"It{RIGHT_QUOTE}s ", "It is ")
        text = text.replace(f"it{RIGHT_QUOTE}s.", "it is.")
        text = text.replace(f"It{RIGHT_QUOTE}s.", "It is.")
        
        # Additional contractions
        text = text.replace(f"we{RIGHT_QUOTE}re ", "we are ")
        text = text.replace(f"We{RIGHT_QUOTE}re ", "We are ")
        text = text.replace(f"y{RIGHT_QUOTE}know", "you know")
        text = text.replace(f"Y{RIGHT_QUOTE}know", "You know")
        text = text.replace(f"can{RIGHT_QUOTE}t", "cannot")
        text = text.replace(f"Can{RIGHT_QUOTE}t", "Cannot")
        text = text.replace(f"won{RIGHT_QUOTE}t", "will not")
        text = text.replace(f"Won{RIGHT_QUOTE}t", "Will not")
        
        # Step 3: For any missed contractions, try regex with word boundary
        # This catches any other apostrophe types or positions we missed
        contraction_patterns = [
            (r"\blet['`′´']s\b", "let us"),
            (r"\bLet['`′´']s\b", "Let us"),
            (r"\bmust['`′´']ve\b", "must have"),
            (r"\bMust['`′´']ve\b", "Must have"),
            (r"\bI['`′´']m\b", "I am"),
            (r"\bi['`′´']m\b", "I am"),
            (r"\bdon['`′´']t\b", "do not"),
            (r"\bDon['`′´']t\b", "Do not"),
            (r"\byou['`′´']re\b", "you are"),
            (r"\bYou['`′´']re\b", "You are"),
            (r"\bthey['`′´']re\b", "they are"),
            (r"\bThey['`′´']re\b", "They are"),
            (r"\bit['`′´']s\b", "it is"),
            (r"\bIt['`′´']s\b", "It is"),
            (r"\byou['`′´']ll\b", "you will"),
            (r"\bYou['`′´']ll\b", "You will"),
            (r"\bthere['`′´']ll\b", "there will"),
            (r"\bThere['`′´']ll\b", "There will"),
        ]
        
        for pattern, replacement in contraction_patterns:
            text = re.sub(pattern, replacement, text)
        
        # Step 4: Add spaces around punctuation
        text = re.sub(r'([.,!?:;()\[\]{}])', r' \1 ', text)
        
        # Step 5: Clean up whitespace
        text = ' '.join(text.split())
        
        processed_texts.append(text)
    
    # Add to DataFrame
    df['processed_text'] = processed_texts
    
    # Display sample results
    print("PROCESSING RESULTS (SAMPLE):")
    for i, (orig, proc) in enumerate(zip(df['text'].head(5), df['processed_text'].head(5))):
        print(f"Row {i}:")
        print(f"  Original: '{orig}'")
        print(f"  Processed: '{proc}'")
        print()
    
    # Return the processed DataFrame
    return df

In [2]:
# Load the data from the specified path
df = pd.read_csv(r"C:\Users\vikku\Downloads\go_emotions.csv")
df

,Unnamed: 0,text,emotion,sub emotion
0,0,That game hurt.,sadness,sadness
1,2,"You do right, if you don't care then fuck 'em!",neutral,neutral
2,3,Man I love reddit.,happiness,love
3,4,"[NAME] was nowhere near them, he was by the Fa...",neutral,neutral
4,5,Right? Considering it’s such an important docu...,happiness,gratitude
...,...,...,...,...
171815,211219,"Well, I'm glad you're out of all that now. How...",happiness,joy
171816,211220,Everyone likes [NAME].,happiness,love
171817,211221,Well when you’ve imported about a gazillion of...,happiness,caring
171818,211222,That looks amazing,happiness,admiration
171819,211223,The FDA has plenty to criticize. But like here...,angry,anger

In [3]:
# Process the DataFrame and get the result
processed_df = robust_contraction_processor(df)

PROCESSING RESULTS (SAMPLE):
Row 0:
  Original: 'That game hurt.'
  Processed: 'That game hurt .'

Row 1:
  Original: 'You do right, if you don't care then fuck 'em!'
  Processed: 'You do right , if you do not care then fuck 'em !'

Row 2:
  Original: 'Man I love reddit.'
  Processed: 'Man I love reddit .'

Row 3:
  Original: '[NAME] was nowhere near them, he was by the Falcon. '
  Processed: '[ NAME ] was nowhere near them , he was by the Falcon .'

Row 4:
  Original: 'Right? Considering it’s such an important document, I should know the damned thing backwards and forwards... thanks again for the help!'
  Processed: 'Right ? Considering it is such an important document , I should know the damned thing backwards and forwards . . . thanks again for the help !'

In [4]:
processed_df

,Unnamed: 0,text,emotion,sub emotion,processed_text
0,0,That game hurt.,sadness,sadness,That game hurt .
1,2,"You do right, if you don't care then fuck 'em!",neutral,neutral,"You do right , if you do not care then fuck 'em !"
2,3,Man I love reddit.,happiness,love,Man I love reddit .
3,4,"[NAME] was nowhere near them, he was by the Fa...",neutral,neutral,"[ NAME ] was nowhere near them , he was by the..."
4,5,Right? Considering it’s such an important docu...,happiness,gratitude,Right ? Considering it is such an important do...
...,...,...,...,...,...
171815,211219,"Well, I'm glad you're out of all that now. How...",happiness,joy,"Well , I am glad you are out of all that now ...."
171816,211220,Everyone likes [NAME].,happiness,love,Everyone likes [ NAME ] .
171817,211221,Well when you’ve imported about a gazillion of...,happiness,caring,Well when you’ve imported about a gazillion of...
171818,211222,That looks amazing,happiness,admiration,That looks amazing
171819,211223,The FDA has plenty to criticize. But like here...,angry,anger,The FDA has plenty to criticize . But like her...

In [6]:
# Save df
processed_df.to_csv(r"C:\Users\vikku\OneDrive\Documenten\Buas\2024-25c-fai2-adsai-group-group21\task 5 - Model Iterations\Logistic Regression\Data\go_emotions.csv", index=False)